en:
  greeting_message: "Hi! Telegram is awesome!"
  help_message: "Help"
  farewell_message: "Bye! I'll miss you :("
  deploy_message: "@%{username} lagi <b>deploy</b> branch <b>%{branch}</b> ke http://www.%{staging}"
  backburner:restart_message: "@%{username} lagi <b>restart backburner</b> branch <b>%{branch}</b> ke http://www.%{staging}"
  backburner:start_message: "@%{username} lagi <b>start backburner</b> branch <b>%{branch}</b> ke http://www.%{staging}"
  backburner:stop_message: "@%{username} lagi <b>stop backburner</b> branch <b>%{branch}</b> ke http://www.%{staging}"
  lock:release_message: "@%{username} lagi <b>lock release</b> branch <b>%{branch}</b> ke http://www.%{staging}"
  fail_message: "ada kesalahan woi @%{username}!, gw pukul juga neh lama2"
  user_not_registered: "username @%{username} dengan id %{chat_id} belum terdaftar, silahkan tambahkan sendiri, atau kasih highfive 10 ke @wiskarindra biar bisa lansung didaftarkan"
